{% set version = "0.8.0" %}

package:
  name: dagmc_h5m_file_inspector
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/d/dagmc_h5m_file_inspector/dagmc_h5m_file_inspector-{{ version }}.tar.gz
  sha256: 5009120a7213a2460e8a32e487cf464d3bc6e6ce9575d56b374178e5336685d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy

test:
  imports:
    - dagmc_h5m_file_inspector
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fusion-energy/dagmc_h5m_file_inspector
  summary: Extracts information from DAGMC h5m files including volumes number, material tags
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shimwell
